title: "Christian Sanchez"
#email: ""
description: "R&D Software Engineer specializing in AI & Distributed Systems."
baseurl: "/portfolio" 
url: "https://christiansanchezde.github.io" 
github_username: alexdev
linkedin_username: alexdev
#scholar_url: ""

# Build settings
markdown: kramdown