title: "Christian Sanchez"
#email: ""
description: "R&D Software Engineer"
baseurl: "/portfolio" 
url: "https://christiansanchezde.github.io" 
github_username: christiansanchezde
linkedin_username: christiansanchezde
#scholar_url: ""

# Build settings
markdown: kramdown